const constants = {
  common: {
    goStudy: 'go.study',
  },
  signin: {
    welcome: 'Welcome!',
    signInAs: 'Sign in as a ',
    email: 'email',
    password: 'password',
    signIn: 'Sign In',
    forgotPassword: 'Forgot password?',
    createAccount: 'Create an account',
    signInWithGoogle: 'Sign in with Google',
  },
  passwordReset: {
    reset: 'Reset',
    forgotPassword: 'Forgot password?',
    resetLinkSent: 'A reset link has been sent to your email address',
    regexString: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$',
  },
  signup: {
    forms: {
      signInWithGoogle: 'Sign in with Google',
      next: 'Next',
      placeHolders: {
        firstName: 'First Name',
        lastName: 'Last Name',
        email: 'Email',
        phone: 'Phone',
        password: 'Password',
        confirmPassword: 'Confirm Password',
      },
    },
    selectCampus: {
      findYourCampus: 'Find your campus',
      selectYourCampus: 'Select your campus',
      finish: 'Finish',
      placeHolders: {
        searchCampus: 'Search your campus...',
      },
    },
    userType: {
      identity: 'I am a',
      student: 'Student',
      tutor: 'Tutor',
    },
  },
  home: {
    hey: 'Hey',
    lookingFor: 'What are you looking for?',
    findTutor: 'Find a Tutor',
    findGroup: 'Find a Study Group',
    myChats: 'My Chats',
  },
  chat: {
    chatHeader: {
      Book: 'Book',
      ViewDetails: 'View Details',
    },
  },
  chatInbox: {
    pageHeader: {
      myChats: 'My Chats',
      placeholder: 'Placeholder',
    },
  },
  commonComponents: {
    sidebar: {
      profile: 'Profile',
      mySessions: 'My Sessions',
      paymentOptions: 'Payment Options',
      tutorCalendar: 'My Calendar',
      accountHistory: 'Account History',
      selectCampus: 'Select Campus',
      signout: 'Sign out',
      termsAndConditions: 'Terms and Conditions',
    },
  },
  editCampuses: {
    addACampus: 'Add a campus',
    confirm: 'Confirm',
    selectACampus: 'Select a campus',
    remove: 'REMOVE',
    editCourses: 'Edit Courses',
    empty: 'empty',
    addAClass: 'Add a class',
    yourClasses: 'Your Classes',
    saveChanges: 'Save Changes',
    removeCampus: 'Remove Campus',
    yourCampus: 'Your Campus',
    placeholder: 'placeholder',
    noAssociatedCampuses: 'You have no associated campuses',
    pressOnCampusToEditClasses: 'Press on a campus to edit its classes',
    pressToChange: 'Press on your campus to modify it',
    yourCampuses: 'Your Campuses',
  },
  profile: {
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone Number',
    password: 'Password',
    changePassword: 'change password',
    description: 'Description',
    id: 'ID',
    termsAndConditions: 'Terms & Conditions',
    profile: 'Profile',
    save: 'Save',
  },
  tutorSearch: {},
  groupSearch: {},
  paymentOptions: {
    title: 'Payment',
    paymentMethod: 'Payment Method',
    connectStripe: 'Connect to your STRIPE account',
    accessStripe: 'Access your STRIPE portal',
    dashBoardUrl: 'https://dashboard.stripe.com/login',
  },
};

export default constants;
